---
- name: Install personal tech stack 
  hosts: localhost

  pre_tasks:
  - name: Update repositories
    become: true
    ansible.builtin.apt:
      update_cache: yes
    changed_when: False

  vars:
    hack_version: "3.003"
    nerd_symbol_version: "3.0.01"
    bottom_version: "0.9.1"
    tmux_plugins_path: "~/.tmux/plugins/"

  tasks:
    - name: Setup core components
      ansible.builtin.include_tasks: "tasks/core.yaml"

    - name: Install Rust
      ansible.builtin.include_tasks: "tasks/rust.yaml"

    - name: Install Starship
      ansible.builtin.include_tasks: "tasks/starship.yaml"

    - name: Install zsh
      ansible.builtin.include_tasks: "tasks/zsh.yaml"

    - name: Install fonts
      ansible.builtin.include_tasks: "tasks/fonts.yaml"

    - name: Install additional tooling
      ansible.builtin.include_tasks: "tasks/tools.yaml"

    - name: Setup VSCode
      ansible.builtin.include_tasks: "tasks/vscode.yaml"

    - name: Install Docker
      ansible.builtin.include_tasks: "tasks/docker.yaml"

    - name: Build neovim nightly
      ansible.builtin.include_tasks: "tasks/neovim_nightly.yaml"
      tags:
        - nightly